services:
  api:
    build:
      context: ./csp
      dockerfile: dockerfile
    container_name: onboard-week3-csp
    ports:
      - "2222:22"
    volumes:
      - ~/.ssh/id_ed25519.pub:/root/.ssh/authorized_keys:ro 
    restart: unless-stopped